# Generated by Django 6.0.2 on 2026-03-31 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('host_session_key', models.CharField(blank=True, max_length=64)),
                ('max_players', models.PositiveSmallIntegerField(default=2)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('BETTING', 'Betting'), ('PLAYER_TURN', 'Player Turn'), ('DEALER_TURN', 'Dealer Turn'), ('ROUND_OVER', 'Round Over')], default='WAITING', max_length=20)),
                ('engine_state', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TableParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_index', models.PositiveSmallIntegerField()),
                ('name', models.CharField(default='Player', max_length=32)),
                ('session_key', models.CharField(max_length=64)),
                ('is_host', models.BooleanField(default=False)),
                ('is_ready', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='Game.gametable')),
            ],
            options={
                'ordering': ['seat_index'],
                'unique_together': {('table', 'seat_index'), ('table', 'session_key')},
            },
        ),
    ]
